% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={A Multiple Linear Model for Toronto and Mississauga House Prices},
  pdfauthor={Ziqian Qiu ID1004723383},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{A Multiple Linear Model for Toronto and Mississauga House Prices}
\author{Ziqian Qiu ID1004723383}
\date{December 3rd, 2020}

\begin{document}
\maketitle

\hypertarget{i.-data-wrangling}{%
\subsection{I. Data Wrangling}\label{i.-data-wrangling}}

a). I use set.seed(1004723383) to set my seed of your randomization and
select a sample of 150 cases. All 150 ids for my chosen sample is shown
below

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1004723383}\NormalTok{)}
\NormalTok{data_AQ3383 =}\StringTok{ }\NormalTok{original_data_AQ3383[}\KeywordTok{sample}\NormalTok{(}\KeywordTok{nrow}\NormalTok{(original_data_AQ3383), }\DecValTok{150}\NormalTok{), ]}
\NormalTok{id_AQ3383 =}\StringTok{ }\NormalTok{data_AQ3383[, }\DecValTok{1}\NormalTok{]}
\NormalTok{id_AQ3383}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1]  38  55  80  75 108 193 103   4 161 140  82 167  15  98 133  28 109  95
##  [19]  19 147  47  21 144  13 118   3 170 177 172 116 155  26 138 105  94  78
##  [37]  32  68  66 112 182  63 229  44 153  86  65 154  20  33  79 207  99 131
##  [55]  45 145  97  40 122 162  64  14 194 175  83 204  43  27 183  29  42 113
##  [73]  57 117 106  69  17 165  74 156  54 119  60 141  30 135  51  67 160 169
##  [91] 136  58 157  31 164  22 158  41  50  36 115  85 104 152  48 179  89 171
## [109]  93  53  90 174 149 163   7 110  91 227 111 139  34  56 125   9  61  24
## [127]  84   2  92 166   8  76  73  81   5 168 126  96  87  37 151 185  72 201
## [145]  52 190 137 218  10 143
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lotsize=data_AQ3383}\OperatorTok{$}\NormalTok{lotwidth}\OperatorTok{*}\NormalTok{data_AQ3383}\OperatorTok{$}\NormalTok{lotlength}
\NormalTok{data_AQ3383 =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(data_AQ3383, lotsize)}
\NormalTok{data_AQ3383 <-}\StringTok{ }\NormalTok{data_AQ3383[,}\OperatorTok{-}\DecValTok{9}\NormalTok{]}
\NormalTok{data_AQ3383 <-}\StringTok{ }\NormalTok{data_AQ3383[,}\OperatorTok{-}\DecValTok{9}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

b). I create a new variable with the name `lotsize' by lotwidth *
lotlength, and add it back into our data frame.

\begin{verbatim}
##        ID              sale              list            bedroom    
##  Min.   :  2.00   Min.   : 672000   Min.   : 649000   Min.   :1.00  
##  1st Qu.: 50.25   1st Qu.:1149250   1st Qu.:1099000   1st Qu.:3.00  
##  Median : 93.50   Median :1430000   Median :1474500   Median :4.00  
##  Mean   : 98.34   Mean   :1792247   Mean   :1802595   Mean   :3.66  
##  3rd Qu.:148.50   3rd Qu.:2142625   3rd Qu.:2073475   3rd Qu.:4.00  
##  Max.   :229.00   Max.   :5100000   Max.   :5499000   Max.   :7.00  
##                                                                     
##     bathroom        parking        maxsqfoot        taxes           location
##  Min.   :1.000   Min.   : 0.00   Min.   :1500   Min.   :    4.375   M:51    
##  1st Qu.:2.000   1st Qu.: 1.25   1st Qu.:2000   1st Qu.: 4511.250   T:99    
##  Median :3.000   Median : 2.00   Median :2500   Median : 6008.500           
##  Mean   :3.333   Mean   : 3.19   Mean   :2908   Mean   : 7121.876           
##  3rd Qu.:4.000   3rd Qu.: 4.00   3rd Qu.:3500   3rd Qu.: 8019.500           
##  Max.   :8.000   Max.   :12.00   Max.   :5000   Max.   :25575.000           
##                  NA's   :8       NA's   :85                                 
##     lotsize       
##  Min.   :  297.4  
##  1st Qu.: 2297.5  
##  Median : 3270.0  
##  Mean   : 5887.3  
##  3rd Qu.: 6000.0  
##  Max.   :55756.0  
##  NA's   :2
\end{verbatim}

c). According to summary shown above, we can tell there are 8 NAs in
parking column, 2 NAs in lotsize and 85 NAs in maxsqfoot. Since we are
allowed to remove a maximize of 11 cases, I removed all 8 cases which
are NA for parking and 2 cases which are NA for lotsize. I also removed
predictor ``maxsqfoot''. This is because its meaning is very similar to
lotwidth, and it has too many NAs, therefore it's not the best to remove
all cases since that's almost half of the total, but simply take the
column out of our data frame. After finishing cleaning data, we have 140
cases left.

\hypertarget{ii.-exploratory-data-analysis}{%
\subsection{II. Exploratory Data
Analysis}\label{ii.-exploratory-data-analysis}}

a). Categorical: location

Discrete: bedrooms, bathrooms, parking

Continuous: sale, list, taxes, lotsize

\begin{verbatim}
##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]
## [1,] 1.0000 0.4657 0.6147 0.2008 0.7556 0.3925
## [2,] 0.4657 1.0000 0.5520 0.3336 0.3751 0.2761
## [3,] 0.6147 0.5520 1.0000 0.3487 0.4653 0.3354
## [4,] 0.2008 0.3336 0.3487 1.0000 0.3690 0.7211
## [5,] 0.7556 0.3751 0.4653 0.3690 1.0000 0.5816
## [6,] 0.3925 0.2761 0.3354 0.7211 0.5816 1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pairs}\NormalTok{(sale}\OperatorTok{~}\NormalTok{list}\OperatorTok{+}\NormalTok{bedroom}\OperatorTok{+}\NormalTok{bathroom}\OperatorTok{+}\NormalTok{parking}\OperatorTok{+}\NormalTok{taxes}\OperatorTok{+}\NormalTok{lotsize, }\DataTypeTok{data =}\NormalTok{ df_AQ3383, }\DataTypeTok{main=}\StringTok{"scatterplot matrix AQ3383"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A3_a20_RMForm_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numericxy=}\KeywordTok{cbind}\NormalTok{(df_AQ3383}\OperatorTok{$}\NormalTok{sale,numericx)}
\KeywordTok{round}\NormalTok{(}\KeywordTok{cor}\NormalTok{(numericxy), }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]
## [1,] 1.0000 0.9885 0.4607 0.6015 0.1623 0.7713 0.3784
## [2,] 0.9885 1.0000 0.4657 0.6147 0.2008 0.7556 0.3925
## [3,] 0.4607 0.4657 1.0000 0.5520 0.3336 0.3751 0.2761
## [4,] 0.6015 0.6147 0.5520 1.0000 0.3487 0.4653 0.3354
## [5,] 0.1623 0.2008 0.3336 0.3487 1.0000 0.3690 0.7211
## [6,] 0.7713 0.7556 0.3751 0.4653 0.3690 1.0000 0.5816
## [7,] 0.3784 0.3925 0.2761 0.3354 0.7211 0.5816 1.0000
\end{verbatim}

b). pairwise correlations and scatterplot matrix for all pairs of
quantitative variables in the data are shown above. The rank of each
quantitative predictor for sale price in terms their correlation
coefficient, from highest to lowest is list(0.9885) \textgreater{}
taxes(0.7713) \textgreater{} bathroom(0.6015) \textgreater{}
bedroom(0.4607) \textgreater{} lotsize(0.3784) \textgreater{}
parking(0.1623)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model_violated =}\StringTok{ }\KeywordTok{lm}\NormalTok{(df_AQ3383}\OperatorTok{$}\NormalTok{sale}\OperatorTok{~}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{bedroom)}
\KeywordTok{plot}\NormalTok{(model_violated, }\DataTypeTok{which=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A3_a20_RMForm_files/figure-latex/unnamed-chunk-7-1.pdf}

c). Based on scatterplot matrix, bedroom of sale price would strongly
violate the assumption of constant variance. The graph shown above is a
SLR of sale price and number of bedrooms.

\hypertarget{iii.-methods-and-model}{%
\subsection{III. Methods and Model}\label{iii.-methods-and-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model_AQ3383 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(df_AQ3383}\OperatorTok{$}\NormalTok{sale}\OperatorTok{~}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{list}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{bedroom}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{bathroom}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{parking}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{taxes}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{location}\OperatorTok{+}\NormalTok{df_AQ3383}\OperatorTok{$}\NormalTok{lotsize)}
\KeywordTok{summary}\NormalTok{(model_AQ3383)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bedroom + 
##     df_AQ3383$bathroom + df_AQ3383$parking + df_AQ3383$taxes + 
##     df_AQ3383$location + df_AQ3383$lotsize)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -386937  -81066  -10215   65030  586379 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)          4.519e+04  5.735e+04   0.788   0.4322    
## df_AQ3383$list       8.377e-01  2.185e-02  38.334  < 2e-16 ***
## df_AQ3383$bedroom    1.021e+04  1.489e+04   0.686   0.4940    
## df_AQ3383$bathroom   1.394e+04  1.321e+04   1.055   0.2933    
## df_AQ3383$parking   -1.616e+04  8.832e+03  -1.830   0.0695 .  
## df_AQ3383$taxes      2.040e+01  4.591e+00   4.443 1.86e-05 ***
## df_AQ3383$locationT  8.126e+04  3.889e+04   2.090   0.0386 *  
## df_AQ3383$lotsize    1.424e+00  2.282e+00   0.624   0.5337    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 130200 on 132 degrees of freedom
## Multiple R-squared:  0.9821, Adjusted R-squared:  0.9812 
## F-statistic:  1037 on 7 and 132 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
  above is additive linear regression model with all available
  predictors variables for sale price. According to graph shown above,
  list price and taxes has significant t-test results. This shows:
  Holding all other explanatory variables in the model fixed, for every
  \$1 increase in the list price, on average sale price increases by 84
  cents. Holding all other explanatory variables in the model fixed, for
  every \$1 increase in taxes, on average sale price increases by
  \$20.4.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AIC_model_AQ3383 =}\StringTok{ }\KeywordTok{step}\NormalTok{(model_AQ3383, }\DataTypeTok{direction =} \StringTok{"backward"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=3305.33
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bedroom + df_AQ3383$bathroom + 
##     df_AQ3383$parking + df_AQ3383$taxes + df_AQ3383$location + 
##     df_AQ3383$lotsize
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$lotsize   1 6.6052e+09 2.2452e+12 3303.7
## - df_AQ3383$bedroom   1 7.9768e+09 2.2466e+12 3303.8
## - df_AQ3383$bathroom  1 1.8882e+10 2.2575e+12 3304.5
## <none>                             2.2386e+12 3305.3
## - df_AQ3383$parking   1 5.6791e+10 2.2954e+12 3306.8
## - df_AQ3383$location  1 7.4055e+10 2.3127e+12 3307.9
## - df_AQ3383$taxes     1 3.3477e+11 2.5734e+12 3322.8
## - df_AQ3383$list      1 2.4922e+13 2.7161e+13 3652.8
## 
## Step:  AIC=3303.75
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bedroom + df_AQ3383$bathroom + 
##     df_AQ3383$parking + df_AQ3383$taxes + df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$bedroom   1 6.9400e+09 2.2522e+12 3302.2
## - df_AQ3383$bathroom  1 1.7542e+10 2.2628e+12 3302.8
## <none>                             2.2452e+12 3303.7
## - df_AQ3383$parking   1 5.2185e+10 2.2974e+12 3305.0
## - df_AQ3383$location  1 7.2162e+10 2.3174e+12 3306.2
## - df_AQ3383$taxes     1 4.1135e+11 2.6566e+12 3325.3
## - df_AQ3383$list      1 2.5095e+13 2.7341e+13 3651.7
## 
## Step:  AIC=3302.18
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bathroom + df_AQ3383$parking + 
##     df_AQ3383$taxes + df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$bathroom  1 3.0249e+10 2.2824e+12 3302.0
## <none>                             2.2522e+12 3302.2
## - df_AQ3383$parking   1 4.5876e+10 2.2981e+12 3303.0
## - df_AQ3383$location  1 8.3458e+10 2.3356e+12 3305.3
## - df_AQ3383$taxes     1 4.1236e+11 2.6645e+12 3323.7
## - df_AQ3383$list      1 2.5227e+13 2.7479e+13 3650.4
## 
## Step:  AIC=3302.05
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$parking + df_AQ3383$taxes + 
##     df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## <none>                             2.2824e+12 3302.0
## - df_AQ3383$parking   1 4.4557e+10 2.3270e+12 3302.8
## - df_AQ3383$location  1 6.2997e+10 2.3454e+12 3303.9
## - df_AQ3383$taxes     1 3.8801e+11 2.6704e+12 3322.0
## - df_AQ3383$list      1 3.7569e+13 3.9852e+13 3700.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AIC_model_AQ3383}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$parking + 
##     df_AQ3383$taxes + df_AQ3383$location)
## 
## Coefficients:
##         (Intercept)       df_AQ3383$list    df_AQ3383$parking  
##           9.905e+04            8.554e-01           -1.195e+04  
##     df_AQ3383$taxes  df_AQ3383$locationT  
##           2.048e+01            7.081e+04
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  As shown above, by using AIC, and the final model is sale = 99050 +
  0.8554list + 20.48taxes - 0.1195parking + 70810locationT. List and
  taxes are consistent as part i). However, parking and location are
  additional predictors that are also discovered by using backward
  elimination of AIC.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BIC_model_AQ3383 =}\StringTok{ }\KeywordTok{step}\NormalTok{(model_AQ3383, }\DataTypeTok{direction =} \StringTok{"backward"}\NormalTok{, }\DataTypeTok{k=}\KeywordTok{log}\NormalTok{(}\DecValTok{150}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=3329.42
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bedroom + df_AQ3383$bathroom + 
##     df_AQ3383$parking + df_AQ3383$taxes + df_AQ3383$location + 
##     df_AQ3383$lotsize
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$lotsize   1 6.6052e+09 2.2452e+12 3324.8
## - df_AQ3383$bedroom   1 7.9768e+09 2.2466e+12 3324.9
## - df_AQ3383$bathroom  1 1.8882e+10 2.2575e+12 3325.6
## - df_AQ3383$parking   1 5.6791e+10 2.2954e+12 3327.9
## - df_AQ3383$location  1 7.4055e+10 2.3127e+12 3329.0
## <none>                             2.2386e+12 3329.4
## - df_AQ3383$taxes     1 3.3477e+11 2.5734e+12 3343.9
## - df_AQ3383$list      1 2.4922e+13 2.7161e+13 3673.8
## 
## Step:  AIC=3324.82
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bedroom + df_AQ3383$bathroom + 
##     df_AQ3383$parking + df_AQ3383$taxes + df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$bedroom   1 6.9400e+09 2.2522e+12 3320.2
## - df_AQ3383$bathroom  1 1.7542e+10 2.2628e+12 3320.9
## - df_AQ3383$parking   1 5.2185e+10 2.2974e+12 3323.0
## - df_AQ3383$location  1 7.2162e+10 2.3174e+12 3324.2
## <none>                             2.2452e+12 3324.8
## - df_AQ3383$taxes     1 4.1135e+11 2.6566e+12 3343.4
## - df_AQ3383$list      1 2.5095e+13 2.7341e+13 3669.7
## 
## Step:  AIC=3320.24
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$bathroom + df_AQ3383$parking + 
##     df_AQ3383$taxes + df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$bathroom  1 3.0249e+10 2.2824e+12 3317.1
## - df_AQ3383$parking   1 4.5876e+10 2.2981e+12 3318.1
## <none>                             2.2522e+12 3320.2
## - df_AQ3383$location  1 8.3458e+10 2.3356e+12 3320.3
## - df_AQ3383$taxes     1 4.1236e+11 2.6645e+12 3338.8
## - df_AQ3383$list      1 2.5227e+13 2.7479e+13 3665.4
## 
## Step:  AIC=3317.1
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$parking + df_AQ3383$taxes + 
##     df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## - df_AQ3383$parking   1 4.4557e+10 2.3270e+12 3314.8
## - df_AQ3383$location  1 6.2997e+10 2.3454e+12 3315.9
## <none>                             2.2824e+12 3317.1
## - df_AQ3383$taxes     1 3.8801e+11 2.6704e+12 3334.1
## - df_AQ3383$list      1 3.7569e+13 3.9852e+13 3712.5
## 
## Step:  AIC=3314.8
## df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$taxes + df_AQ3383$location
## 
##                      Df  Sum of Sq        RSS    AIC
## <none>                             2.3270e+12 3314.8
## - df_AQ3383$taxes     1 3.6357e+11 2.6906e+12 3330.1
## - df_AQ3383$location  1 3.6570e+11 2.6927e+12 3330.2
## - df_AQ3383$list      1 3.8856e+13 4.1183e+13 3712.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BIC_model_AQ3383}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = df_AQ3383$sale ~ df_AQ3383$list + df_AQ3383$taxes + 
##     df_AQ3383$location)
## 
## Coefficients:
##         (Intercept)       df_AQ3383$list      df_AQ3383$taxes  
##           5.045e+04            8.490e-01            1.970e+01  
## df_AQ3383$locationT  
##           1.148e+05
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  As shown above, by using AIC, and the final model is sale = 50450 +
  0.8490list + 19.70taxes + 114800locationT. List and taxes are
  consistent as part i) and ii). However, compared to part i), which is
  using backward elimination by AIC, parking is no longer highlighted by
  using backward elimination of BIC.
\end{enumerate}

\hypertarget{iv.-discussions-and-limitations}{%
\subsection{IV. Discussions and
Limitations}\label{iv.-discussions-and-limitations}}

Part 4 (.)

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(BIC_model_AQ3383, }\DataTypeTok{main =} \StringTok{"                                              AQ3383"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A3_a20_RMForm_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Four diagnostic plots that are obtained in R by plotting the model
  obtained in part III iii) is shown above.
\end{enumerate}

\begin{verbatim}
##     77     45     31     35     61     88      5     18    130     41      1 
## 0.2957 0.0993 0.0918 0.0619 0.0497 0.0493 0.0428 0.0405 0.0298 0.0233 0.0221 
##     95 
## 0.0213
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Residuals vs Fitted: the residuals are equally distributed above and
  under the horizontal line. This indicated we have a linear
  relationship. Case 45 and 61 seems a little bit off, but we don't know
  what it is yet, so we'll keep that in mind. Normal Q-Q: We can tell
  the residuals almost follow a straight line and barely deviate, but
  case 45 and 61 still concerns us. Note that we don't have a heavy tale
  here, which is good. Scale-Location: a horizontal line shows majority
  of the residuals is spread equally along the range of predictors. This
  also shows we have homoscedasticity. As shown above in the previous
  graphs, case 45 is more irregular than case 61 here. Residuals vs
  Leverage: This is where we defines influential points, which are cases
  outside the dashed line called ``cook's distance''. According to code
  shown above, cases with cooks distance does not have a significant
  effect in the model. Therefore, we can concluded that neither case 45
  nor case 61 are influential points, and according to four graphs
  above, we can safely say the model satisfies normality assumptions,
  constant variance and linearity.
\end{enumerate}

c). In order to find a valid final model, I would probably fix the
problem for ``maxsqfoot'', which is the predictor we eliminated from the
beginning since most of cases is missing its value. I would also add a
few more predictors, for example, history rent prices. This makes sense
because when purchasing a property as an investment, it's sale price is
always dependents on how much it can rent. If possible, using anova to
calculate the F-tests is also a valid way to highlight the predictors of
the model.

\end{document}
